{
  "api_test/test_getuser.py::Test_callapi::test_errorcode": true
}